# Generated by Django 4.1.3 on 2024-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="travel_preferences",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
