# Generated by Django 4.1.3 on 2024-11-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_budget_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget_range',
            field=models.IntegerField(blank=True, default='', max_length=50, null=True),
        ),
    ]
