# Generated by Django 5.0 on 2024-11-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_profile_delete_customer"),
        ("customer", "0005_alter_profile_budget_range"),
    ]

    operations = []
