# Generated by Django 5.0 on 2024-12-29 14:10

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('guide', '0002_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiderequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guiderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 14, 13, 48, 996784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guiderequest',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide'),
        ),
        migrations.AlterField(
            model_name='guiderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('time_out', 'Timed Out')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='guiderequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('guide_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.guiderequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
