# Generated by Django 5.0 on 2024-12-31 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_guiderequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiderequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 15, 19, 9, 309562, tzinfo=datetime.timezone.utc)),
        ),
    ]
